version: '3.9'

services:
  haproxy:
    image: local/haproxy:latest
    restart: always
    container_name: haproxy
    build:
      context: haproxy/
    ports:
      - "8080:80"
      - "8404:8404"
    links:
      - nginx_server1
      - nginx_server2
  nginx_server1:
    image: local/nginx:1.23.1
    restart: always
    container_name: nginx_server1
    build:
      context: nginx/
  nginx_server2:
    image: local/nginx:1.23.1
    restart: always
    container_name: nginx_server2
    build:
      context: nginx/
    